In [3]:
#PART 1 — NumPy Fundamentals
import numpy as np
import pandas as pd

In [14]:
#Array creation
#1. Create a 1-D NumPy array containing the numbers 10 to 50 with a step of 5.
arr1=np.arange(10,51,5)
print(arr1)
#2. Create a 3 × 4 array containing only zeros.
arr2=np.zeros((3,4))
print(arr2)
#3.Create a 4 × 3 array containing only ones.
arr3=np.ones((4,3))
print(arr3)
#4.Create a 5 × 5 identity matrix.
arr4=np.eye(5)
print(arr4)
#5.Generate 10 equally spaced numbers between 0 and 1.
arr5=np.linspace(0,1,10)
print(arr5)
#6.Generate the even numbers from 2 to 20.
arr6=np.arange(2,21,2)
print(arr6)

[10 15 20 25 30 35 40 45 50]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 2  4  6  8 10 12 14 16 18 20]

In [18]:
#Array attributes
'''
7. Find its shape.

8. Find its number of dimensions.

9. Find its total number of elements.

10. Find its data type.'''
array=np.array([
 [10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])
print(array.shape)
print(array.ndim)
print(array.size)
print(array.dtype)

(3, 3)
2
9
int64

In [26]:
#Indexing & slicing
'''
11. Extract 50.

12. Extract the first row.

13. Extract the last row.

14. Extract the second column.
15. Extract: 
   [[20, 30],
 [50, 60]]
16. Extract the last two rows.'''

print(array[1,1])
print(array[0,:])
print(array[-1,:])
print(array[:,1])
print(array[:2,1:])
print(array[1:,:])

50
[10 20 30]
[70 80 90]
[20 50 80]
[[20 30]
 [50 60]]
[[40 50 60]
 [70 80 90]]

In [38]:
#PART 2 — NumPy Calculations & Boolean Operations
sales = np.array([12000, 15000, 18000, 9000, 22000, 17000, 25000])
#17. Add ₹2,000 to every value.
print(sales+2000)
#18. Reduce every value by 10%.
print(sales*(100-10)/100)
#19. Calculate the total sales.
print('Total sales',sales.sum())
#20. Calculate average sales.
print('Average sales',sales.mean())
#21. Find median sales.
print('Median sales',np.median(sales))
#22. Find minimum and maximum sales.
print('Minimum sales:',sales.min())
print('Maximum sales:',sales.max())
#23. Calculate standard deviation.
print('Standard deviation:',sales.std())
#24. Calculate variance.
print('Variance',sales.var())
#25. Find all sales greater than ₹15,000.
thres=sales>15000
print(sales[thres])
#26. Find the positions of sales greater than ₹15,000.
indices=np.where(sales>15000)[0]
print(indices)

[14000 17000 20000 11000 24000 19000 27000]
[10800. 13500. 16200.  8100. 19800. 15300. 22500.]
Total sales 118000
Average sales 16857.14285714286
Median sales 17000.0
Minimum sales: 9000
Maximum sales: 25000
Standard deviation: 5111.012519999519
Variance 26122448.97959184
[18000 22000 17000 25000]
[2 4 5 6]

In [44]:
#Broadcasting
monthly_sales = np.array([
    [10000, 12000, 15000],
    [14000, 16000, 18000],
    [20000, 22000, 25000]
])
#28. Add [1000, 2000, 3000] to every row.
hike=np.array([1000, 2000, 3000])
monthly_sales+=hike
print(monthly_sales)
#29. Increase every value by 10%.
print(monthly_sales*1.10)
#30. Calculate the total of each row.
print('Total of each row:',monthly_sales.sum(axis=1))
#31. Calculate the total of each column.
print('Total of each column:',monthly_sales.sum(axis=0))
#32. Calculate the average of each row.
print('Average of each row:',monthly_sales.mean(axis=1))

[[11000 14000 18000]
 [15000 18000 21000]
 [21000 24000 28000]]
[[12100. 15400. 19800.]
 [16500. 19800. 23100.]
 [23100. 26400. 30800.]]
Total of each row: [43000 54000 73000]
Total of each column: [47000 56000 67000]
Average of each row: [14333.33333333 18000.         24333.33333333]

In [51]:
#PART 3 — NumPy Reshaping, Sorting & Linear Algebra
#33.Create an array containing 1–12.
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar)
#34. Reshape it into a 3 × 4 matrix.
ar2=ar.reshape(3,4)
print(ar2)
#35. Reshape it into a 4 × 3 matrix.
ar3=ar.reshape(4,3)
print(ar3)
#37. Convert the matrix back to 1-D without explicitly using flatten().
r=ar2.ravel()
print(r)
#38.sort the array [45, 12, 78, 23, 56, 9, 34]
arr8=np.array([45, 12, 78, 23, 56, 9, 34])
sort=np.sort(arr8)
print(arr8)
print(sort)
#39. Find the positions of values greater than 40.
print(np.where(arr8>40)[0])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[45 12 78 23 56  9 34]
[ 9 12 23 34 45 56 78]
[0 2 4]

In [54]:
#Matrix operations
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
#40. Perform element-wise multiplication.
mul=np.multiply(A,B)
print(mul)
#41. Transpose A.
trans=np.transpose(A)
print(trans)
#42. Calculate the dot product.
dot=np.dot(A,B)
print(dot)

[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]
[[19 22]
 [43 50]]

In [4]:
#PART 4 — Pandas Foundations + NumPy Integration
data = {
    'Name': ['Arun', 'Priya', 'Karthik', 'Meena', 'Rahul', 'Divya'],
    'Age': [24, 29, 35, 27, 41, 31],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT'],
    'Salary': [35000, 52000, 78000, 45000, 92000, 68000],
    'Experience': [2, 5, 10, 3, 15, 7]
}

df = pd.DataFrame(data)
df
#43. Display the first 3 rows.
print(df.head(3))
#Display the last 2 rows.
print(df.tail(2))
#44. Find the shape.
print(df.shape)
#45. Find the column names.
print(df.columns)
#46. Display information about the DataFrame.
print(df.info())
#47. Generate statistical information.
print(df.describe())

      Name  Age Department  Salary  Experience
0     Arun   24         IT   35000           2
1    Priya   29         HR   52000           5
2  Karthik   35         IT   78000          10
    Name  Age Department  Salary  Experience
4  Rahul   41         HR   92000          15
5  Divya   31         IT   68000           7
(6, 5)
Index(['Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         6 non-null      int64
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes
None
             Age        Salary  Experience
count   6.000000      6.000000    6.000000
mean   31.166667  61666.666667    7.000000
std     6.080022  21491.083422    4.857983
min    24.000000  35000.000000    2.000000
25%    27.500000  46750.000000    3.500000
50%    30.000000  60000.000000    6.000000
75%    34.000000  75500.000000    9.250000
max    41.000000  92000.000000   15.000000

In [22]:
#Selection
#48. Select Name.
print(df['Name'])
#49. Select Name and Salary.
print(df[['Name','Salary']])
#50. Select rows 1–3 using positional indexing.
print(df[:3])
#Select the third row using label-based indexing.
print(df.loc[2])
#Select the Name, Department, and Salary columns for rows 2–5.
print(df[['Name','Department','Salary']][1:])

0       Arun
1      Priya
2    Karthik
3      Meena
4      Rahul
5      Divya
Name: Name, dtype: object
      Name  Salary
0     Arun   35000
1    Priya   52000
2  Karthik   78000
3    Meena   45000
4    Rahul   92000
5    Divya   68000
      Name  Age Department  Salary  Experience
0     Arun   24         IT   35000           2
1    Priya   29         HR   52000           5
2  Karthik   35         IT   78000          10
Name          Karthik
Age                35
Department         IT
Salary          78000
Experience         10
Name: 2, dtype: object
      Name Department  Salary
1    Priya         HR   52000
2  Karthik         IT   78000
3    Meena    Finance   45000
4    Rahul         HR   92000
5    Divya         IT   68000

In [30]:
#NumPy + Pandas
#Convert the Salary column into a NumPy array.
sal=df['Salary'].to_numpy()
print(sal)
#Using NumPy, calculate the average salary.
print('Average salary',sal.mean())
#Using NumPy, find the employees' salary values above ₹60,000.
thres=sal>60000
print('Employee salary greater than 60,000',sal[thres])
#Using NumPy, calculate the standard deviation of salary.
print(f'Standard deviation of salary{sal.std():.2f}')
#Convert the resulting NumPy values back into a Pandas-friendly structure and create a new column indicating whether each employee earns above ₹60,000.
df['Earning above 60k']=thres
print(df)

[35000 52000 78000 45000 92000 68000]
Average salary 61666.666666666664
Employee salary greater than 60,000 [78000 92000 68000]
Standard deviation of salary19618.59
      Name  Age Department  Salary  Experience  Earning above 60k
0     Arun   24         IT   35000           2              False
1    Priya   29         HR   52000           5              False
2  Karthik   35         IT   78000          10               True
3    Meena   27    Finance   45000           3              False
4    Rahul   41         HR   92000          15               True
5    Divya   31         IT   68000           7               True

In [37]:
#filtering
#Find employees from IT.
print(df[df['Department']=='IT'])
#Find employees earning more than ₹60,000.
print(df[df['Salary']>60000])
#Find employees with more than 5 years of experience.
print(df[df['Experience']>5])
#Find HR employees earning more than ₹50,000.
print(df[(df['Department']=='HR') & (df['Salary']>50000)])
#Find employees aged above 30 AND earning above ₹60,000.
print(df[(df['Age']>30) & (df['Salary']>60000)])
#Find employees from IT OR HR.
print(df[(df['Department']=='HR') | (df['Department']=='IT')])
#Find employees NOT from Finance.
print(df[~(df['Department']=='Finance')])
#Find employees whose salary is between ₹40,000 and ₹80,000.
print(df[(df['Salary']>39000) & (df['Salary']<81000)])

      Name  Age Department  Salary  Experience  Earning above 60k
0     Arun   24         IT   35000           2              False
2  Karthik   35         IT   78000          10               True
5    Divya   31         IT   68000           7               True
      Name  Age Department  Salary  Experience  Earning above 60k
2  Karthik   35         IT   78000          10               True
4    Rahul   41         HR   92000          15               True
5    Divya   31         IT   68000           7               True
      Name  Age Department  Salary  Experience  Earning above 60k
2  Karthik   35         IT   78000          10               True
4    Rahul   41         HR   92000          15               True
5    Divya   31         IT   68000           7               True
    Name  Age Department  Salary  Experience  Earning above 60k
1  Priya   29         HR   52000           5              False
4  Rahul   41         HR   92000          15               True
      Name  Age Department  Salary  Experience  Earning above 60k
2  Karthik   35         IT   78000          10               True
4    Rahul   41         HR   92000          15               True
5    Divya   31         IT   68000           7               True
      Name  Age Department  Salary  Experience  Earning above 60k
0     Arun   24         IT   35000           2              False
1    Priya   29         HR   52000           5              False
2  Karthik   35         IT   78000          10               True
4    Rahul   41         HR   92000          15               True
5    Divya   31         IT   68000           7               True
      Name  Age Department  Salary  Experience  Earning above 60k
0     Arun   24         IT   35000           2              False
1    Priya   29         HR   52000           5              False
2  Karthik   35         IT   78000          10               True
4    Rahul   41         HR   92000          15               True
5    Divya   31         IT   68000           7               True
      Name  Age Department  Salary  Experience  Earning above 60k
1    Priya   29         HR   52000           5              False
2  Karthik   35         IT   78000          10               True
3    Meena   27    Finance   45000           3              False
5    Divya   31         IT   68000           7               True

In [6]:
#pandas-based classification
#Salary_Level
#Salary < 40000       → Low
#40000–70000          → Medium
#>70000               → High
def salary_level(salary):
    if salary>70000:
        return "High"
    elif salary>40000 and salary<70000:
        return "Medium"
    else:
        return "Low"
#Experience_Level

'''<3       → Junior
3–7      → Mid
>7       → Senior'''
def exp_level(experience):
    if experience>7:
        return "Senior"
    elif experience>=3 and experience<=7:
        return "Mid"
    else:
        return "Junior"
df['Salary_level']=df['Salary'].apply(salary_level)
df['Experience_level']=df["Experience"].apply(exp_level)
df

      Name  Age Department  Salary  Experience Salary_level Experience_level
0     Arun   24         IT   35000           2          Low           Junior
1    Priya   29         HR   52000           5       Medium              Mid
2  Karthik   35         IT   78000          10         High           Senior
3    Meena   27    Finance   45000           3       Medium              Mid
4    Rahul   41         HR   92000          15         High           Senior
5    Divya   31         IT   68000           7       Medium              Mid

In [7]:
#Create a Boolean column indicating employees eligible for promotion:
df['Bonus_eligible']=(df['Experience']>5) & (df['Salary']>60000)
df

,Name,Age,Department,Salary,Experience,Salary_level,Experience_level,Bonus_eligible
0,Arun,24,IT,35000,2,Low,Junior,False
1,Priya,29,HR,52000,5,Medium,Mid,False
2,Karthik,35,IT,78000,10,High,Senior,True
3,Meena,27,Finance,45000,3,Medium,Mid,False
4,Rahul,41,HR,92000,15,High,Senior,True
5,Divya,31,IT,68000,7,Medium,Mid,True

In [34]:
#PART 6 — Pandas Calculations + GroupBy
sales = pd.DataFrame({
    'Employee': ['Arun', 'Priya', 'Karthik', 'Meena', 'Rahul',
                 'Divya', 'Sanjay', 'Anitha'],
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance',
                   'Finance', 'IT', 'HR'],
    'Sales': [45000, 62000, 38000, 55000, 72000,
              68000, 51000, 47000],
    'Units': [12, 18, 9, 15, 21, 19, 14, 11]
})
#Calculate total sales.
print(f"Total Sales {sales['Sales'].sum():.2f}")
#Calculate average sales.
print(f"Average sales {sales['Sales'].mean():.1f}")
#Calculate total units.
print(f"Total units {sales['Units'].sum()}")
#Create a Revenue_Per_Unit column.
sales['Revenue_per_unit']=(sales['Sales']/sales['Units']).round().astype(int)
print(sales)
#Find the employee with the highest sales.
high=sales.loc[sales['Sales'].idxmax()]
print(high)
#Find the employee with the lowest sales.
low=sales.loc[sales['Sales'].idxmin()]
print(low)

Total Sales 438000.00
Average sales 54750.0
Total units 119
  Employee Department  Sales  Units  Revenue_per_unit
0     Arun         IT  45000     12              3750
1    Priya         IT  62000     18              3444
2  Karthik         HR  38000      9              4222
3    Meena         HR  55000     15              3667
4    Rahul    Finance  72000     21              3429
5    Divya    Finance  68000     19              3579
6   Sanjay         IT  51000     14              3643
7   Anitha         HR  47000     11              4273
Employee              Rahul
Department          Finance
Sales                 72000
Units                    21
Revenue_per_unit       3429
Name: 4, dtype: object
Employee            Karthik
Department               HR
Sales                 38000
Units                     9
Revenue_per_unit       4222
Name: 2, dtype: object

In [43]:
#Grouping
#Calculate total sales by department wise
total_sales=sales.groupby('Department')['Sales'].sum()
print("Department wise sales total\n",total_sales)
#Calculate average sales by department.
Avg_sales=sales.groupby('Department')['Sales'].mean()
print("Department wise sales average\n",Avg_sales)
#Calculate total units by department.
Total_units=sales.groupby('Department')['Units'].sum()
print("Departemnt wise units total\n",Total_units)
#Find the maximum sales in each department.
Maximum_sales=sales.groupby('Department')['Sales'].max()
print("Department wise maximum sales\n",Maximum_sales)
#Count employees in each department.
Count=sales.groupby('Department')['Employee'].count()
print("Department wise employees count\n",Count)

Department wise sales total
 Department
Finance    140000
HR         140000
IT         158000
Name: Sales, dtype: int64
Department wise sales average
 Department
Finance    70000.000000
HR         46666.666667
IT         52666.666667
Name: Sales, dtype: float64
Departemnt wise units total
 Department
Finance    40
HR         35
IT         44
Name: Units, dtype: int64
Department wise maximum sales
 Department
Finance    72000
HR         55000
IT         62000
Name: Sales, dtype: int64
Department wise employees count
 Department
Finance    2
HR         3
IT         3
Name: Employee, dtype: int64

In [45]:
#For each department calculate:
'''Total Sales
Average Sales
Maximum Sales
Minimum Sales
Total Units'''
aggregate=sales.groupby('Department')['Sales'].agg(['sum','mean','max','min'])
Total_units=sales.groupby('Department')['Units'].sum()
print("Departemnt wise units total\n",Total_units)
print(aggregate)

Departemnt wise units total
 Department
Finance    40
HR         35
IT         44
Name: Units, dtype: int64
               sum          mean    max    min
Department
Finance     140000  70000.000000  72000  68000
HR          140000  46666.666667  55000  38000
IT          158000  52666.666667  62000  45000

In [59]:
#PART 7 — Data Cleaning + Combining NumPy/Pandas
messy = pd.DataFrame({
    'Name': ['Arun', 'Priya', 'Karthik', 'Meena', 'Rahul'],
    'Age': [25, np.nan, 35, 28, np.nan],
    'Salary': [35000, 52000, np.nan, 45000, 70000],
    'Department': ['IT', 'HR', np.nan, 'Finance', 'HR']
})
#Find all missing values.
print(messy.isnull())
#Count missing values per column.
print(messy.isnull().sum(axis=0))
#Replace missing ages with the median age.
df_clean2 = messy.copy()
df_clean2['Age'].fillna(df['Age'].median(),inplace=True)
print("after adding median age values\n",df_clean2)
#Replace missing salary with the mean salary.
df_clean2['Salary'].fillna(df['Salary'].mean().round(),inplace=True)
print("After adding mean salary values\n",df_clean2)
#Replace missing department with "Unknown"
df_clean2['Department'].fillna('Unknown',inplace=True)
print("After adding unknown in dept\n",df_clean2)
#Remove any remaining rows containing missing values.
print(df_clean2.isnull().sum(axis=0))

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True        True
3  False  False   False       False
4  False   True   False       False
Name          0
Age           2
Salary        1
Department    1
dtype: int64
after adding median age values
       Name   Age   Salary Department
0     Arun  25.0  35000.0         IT
1    Priya  30.0  52000.0         HR
2  Karthik  35.0      NaN        NaN
3    Meena  28.0  45000.0    Finance
4    Rahul  30.0  70000.0         HR
After adding mean salary values
       Name   Age   Salary Department
0     Arun  25.0  35000.0         IT
1    Priya  30.0  52000.0         HR
2  Karthik  35.0  61667.0        NaN
3    Meena  28.0  45000.0    Finance
4    Rahul  30.0  70000.0         HR
After adding unknown in dept
       Name   Age   Salary Department
0     Arun  25.0  35000.0         IT
1    Priya  30.0  52000.0         HR
2  Karthik  35.0  61667.0    Unknown
3    Meena  28.0  45000.0    Finance
4    Rahul  30.0  70000.0         HR
Name          0
Age           0
Salary        0
Department    0
dtype: int64

C:\Users\syeda\AppData\Local\Temp\ipykernel_13748\4035508061.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean2['Age'].fillna(df['Age'].median(),inplace=True)
C:\Users\syeda\AppData\Local\Temp\ipykernel_13748\4035508061.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean2['Salary'].fillna(df['Salary'].mean().round(),inplace=True)
C:\Users\syeda\AppData\Local\Temp\ipykernel_13748\4035508061.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean2['Department'].fillna('Unknown',inplace=True)